import qrcode
import uuid
from datetime import datetime

def generate_certificate_qr():
    # for taking input with user
    name = input("Enter certificate recipient name: ")
    subject = input("Enter subject (e.g., Python, Java, NET): ")
    marks = input("Enter marks/grade (e.g., 92%, A+, 95/100): ")
    
    
    unique_id = datetime.now().strftime("%Y%m%d") + "_" + str(uuid.uuid4())[:8]
    
    #2-------------creating certificate
    certificate_content = f""" CERTIFICATE
========================
Name: {name}
Subject: {subject}
Marks: {marks}
ID: {unique_id}
Date: {datetime.now().strftime('%Y-%m-%d')}
Status: VERIFIED 
========================
Generated by Certificate System"""
    
    # 3 qr code generating
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_H,
        box_size=12,
        border=4,
    )
    qr.add_data(certificate_content)
    qr.make(fit=True)
    
    # 4 Create and save image
    img = qr.make_image(fill_color="blue", back_color="white")
    filename = f"certificate_{name.replace(' ', '_')}_{unique_id}.png"
    img.save(filename)
    
    print(f"\n QR code saved as: {filename}")
    print("=" * 50)
    print(certificate_content)
    print("=" * 50)
    
 

# Run the program
if __name__ == "__main__":
    generate_certificate_qr()
    